import React, { useState } from 'react';
import { 
  UserPlus, 
  Trash2, 
  Edit2, 
  Eye, 
  EyeOff, 
  Key, 
  Mail, 
  CheckCircle, 
  Lock, 
  ShieldCheck, 
  Send,
  Sparkles,
  RefreshCw,
  X
} from 'lucide-react';

interface StaffAccount {
  id: string;
  email: string;
  password: string;
  createdAt: string;
  lastLogin?: string;
}

interface StaffManagementProps {
  staffAccounts: StaffAccount[];
  onCreateStaff: (email: string, password: string) => void;
  onUpdateStaffPassword: (id: string, newPass: string) => void;
  onDeleteStaff: (id: string) => void;
  onSimulateEmailDispatch: (email: string, message: string) => void;
}

export default function StaffManagement({
  staffAccounts,
  onCreateStaff,
  onUpdateStaffPassword,
  onDeleteStaff,
  onSimulateEmailDispatch
}: StaffManagementProps) {
  // Creating staff state (no prefil)
  const [newEmail, setNewEmail] = useState('');
  const [newPassword, setNewPassword] = useState('');
  
  // Password list visibility controls
  const [revealedPasswords, setRevealedPasswords] = useState<Record<string, boolean>>({});
  
  // Inline edit state
  const [editingStaffId, setEditingStaffId] = useState<string | null>(null);
  const [editingPassword, setEditingPassword] = useState('');

  // Simulating sent email log details
  const [lastDispatchedEmail, setLastDispatchedEmail] = useState<{
    to: string;
    subject: string;
    body: string;
    timestamp: string;
  } | null>(null);

  const [formError, setFormError] = useState<string | null>(null);
  const [successMsg, setSuccessMsg] = useState<string | null>(null);

  // Auto-generate strong passcode
  const handleGeneratePassword = () => {
    const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*';
    let pass = '';
    for (let i = 0; i < 10; i++) {
      pass += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    setNewPassword(pass);
    setFormError(null);
  };

  const handleCreateSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);
    setSuccessMsg(null);

    const emailTrimmed = newEmail.trim().toLowerCase();
    const passwordTrimmed = newPassword.trim();

    if (!emailTrimmed || !emailTrimmed.includes('@')) {
      setFormError('Please enter a valid official staff email address.');
      return;
    }

    if (passwordTrimmed.length < 5) {
      setFormError('Password must be at least 5 character credentials elements long.');
      return;
    }

    // Check duplicate
    const isDuplicate = staffAccounts.some(acc => acc.email.toLowerCase() === emailTrimmed) || 
                        emailTrimmed === 'officer@cornerstone.com' ||
                        emailTrimmed === 'admin@cornerstone.com';
    if (isDuplicate) {
      setFormError('This staff directory ID is already registered in the system ledger.');
      return;
    }

    // Create staff account
    onCreateStaff(emailTrimmed, passwordTrimmed);

    // Format secure email contents
    const subject = '🔒 New Administrative Account Portal Credentials - Cornerstone Savings & Loans';
    const body = `Hi Staff,\n\nYour official administrative account portal credentials for the Cornerstone Savings & Loans Ledger System have been generated by the administrator.\n\n------------------------------\nSTAFF LOGIN ID: ${emailTrimmed}\nTEMPORARY PASSCODE: ${passwordTrimmed}\n------------------------------\n\nPlease log in to your official terminal console using the credentials above and review your assigned portfolios.\n\nSecurity notice: Please keep your passcode confidential. Do not share this notification.`;

    // Simulate sending email
    onSimulateEmailDispatch(emailTrimmed, body);

    setLastDispatchedEmail({
      to: emailTrimmed,
      subject,
      body,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })
    });

    setSuccessMsg(`Staff user directory initialized successfully for ${emailTrimmed}!`);
    
    // Clear form
    setNewEmail('');
    setNewPassword('');

    // dismiss message after 5s
    setTimeout(() => setSuccessMsg(null), 5000);
  };

  const togglePasswordReveal = (id: string) => {
    setRevealedPasswords(prev => ({
      ...prev,
      [id]: !prev[id]
    }));
  };

  const startEditing = (id: string, currentPass: string) => {
    setEditingStaffId(id);
    setEditingPassword(currentPass);
  };

  const saveInlineEdit = (id: string) => {
    if (editingPassword.trim().length < 5) {
      alert('Password must be at least 5 characters to ensure system integrity.');
      return;
    }
    onUpdateStaffPassword(id, editingPassword.trim());
    
    // Auto simulate sending updated passcode
    const account = staffAccounts.find(a => a.id === id);
    if (account) {
      const subject = '🔑 Security Update: Passcode Reset Notification';
      const body = `Hi,\n\nYour main administrative workspace passcode has been updated by the Cornerstone Savings Systems admin.\n\n------------------------------\nSTAFF LOGIN ID: ${account.email}\nNEW PASSCODE: ${editingPassword.trim()}\n------------------------------\n\nAccess your profile dashboard immediately using these updated credentials.`;
      onSimulateEmailDispatch(account.email, body);
      setLastDispatchedEmail({
        to: account.email,
        subject,
        body,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })
      });
    }

    setEditingStaffId(null);
  };

  return (
    <div className="space-y-6">
      
      {/* Visual Header */}
      <div className="bg-white rounded-xl p-5 shadow-sm border border-slate-200 flex items-center justify-between">
        <div>
          <h2 className="text-lg font-sans font-bold text-slate-900 flex items-center gap-2">
            <ShieldCheck className="w-5.5 h-5.5 text-indigo-650" />
            Administrative Portal: Staff Account & Vault Registry
          </h2>
          <p className="text-xs text-slate-500">Commission new staff credentials, inspect security tokens, update active directory passwords, and dispatch login notification transcripts.</p>
        </div>
        <div className="bg-indigo-50 text-indigo-600 rounded-lg p-2 border border-indigo-100 flex items-center justify-center">
          <Lock className="w-5 h-5" />
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left column - Create Account Form */}
        <div className="lg:col-span-5 bg-white rounded-xl p-5 shadow-sm border border-slate-200 h-fit space-y-4">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 border-b border-slate-150 pb-2.5 flex items-center gap-1.5">
            <UserPlus className="w-4 h-4 text-indigo-600" />
            Commission New Staff ID
          </h3>

          {formError && (
            <div className="p-3 bg-rose-50 border border-rose-200 text-rose-800 text-xs font-semibold rounded-lg flex items-start gap-2 animate-shake">
              <span className="text-sm select-none">⚠️</span>
              <span>{formError}</span>
            </div>
          )}

          {successMsg && (
            <div className="p-3 bg-emerald-50 border border-emerald-100 text-emerald-800 text-xs font-semibold rounded-lg flex items-start gap-2 animate-fade-in">
              <CheckCircle className="w-4 h-4 text-emerald-600 mt-0.5 flex-shrink-0" />
              <span>{successMsg}</span>
            </div>
          )}

          <form onSubmit={handleCreateSubmit} className="space-y-4 text-left">
            <div className="space-y-1.5">
              <label className="text-xs font-bold text-slate-650">Staff Username/Email</label>
              <div className="relative">
                <Mail className="absolute left-3 top-2.5 w-4 h-4 text-slate-400" />
                <input
                  type="text"
                  placeholder="e.g. officer.name@cornerstonesavings.com"
                  value={newEmail}
                  onChange={(e) => {
                    setNewEmail(e.target.value);
                    setFormError(null);
                  }}
                  className="w-full pl-9 pr-3 py-2 bg-slate-50 border border-slate-200 focus:border-indigo-500 rounded-lg text-xs font-semibold font-sans text-slate-800 transition placeholder-slate-405"
                />
              </div>
              <span className="text-[9px] text-slate-404 block">Use offical @cornerstone domain address.</span>
            </div>

            <div className="space-y-1.5">
              <div className="flex justify-between items-center">
                <label className="text-xs font-bold text-slate-650">Temporary Passcode</label>
                <button
                  type="button"
                  onClick={handleGeneratePassword}
                  className="text-[10px] text-indigo-650 hover:underline font-bold flex items-center gap-0.5 cursor-pointer"
                >
                  <RefreshCw className="w-2.5 h-2.5" /> Generate Strong Passcode
                </button>
              </div>
              <div className="relative">
                <Key className="absolute left-3 top-2.5 w-4 h-4 text-slate-400" />
                <input
                  type="text"
                  placeholder="Enter system passcode or generate automatically"
                  value={newPassword}
                  onChange={(e) => {
                    setNewPassword(e.target.value);
                    setFormError(null);
                  }}
                  className="w-full pl-9 pr-3 py-2 bg-slate-50 border border-slate-200 focus:border-indigo-500 rounded-lg text-xs font-bold font-mono text-slate-800 transition placeholder-slate-405"
                />
              </div>
            </div>

            <button
              type="submit"
              className="w-full py-2 bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs rounded-lg transition flex items-center justify-center gap-1.5 cursor-pointer select-none"
            >
              <UserPlus className="w-4 h-4" /> Commission & Send Login Email
            </button>
          </form>

          {/* Real-time Email Delivery visual notification box */}
          {lastDispatchedEmail && (
            <div className="p-3.5 bg-slate-900 text-white border border-slate-800 rounded-xl mt-4 animate-slide-up text-left space-y-2 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-16 h-16 bg-emerald-500/10 rounded-full blur-xl"></div>
              
              <div className="flex items-center justify-between border-b border-slate-800 pb-1.5">
                <span className="text-[9px] font-mono text-emerald-400 font-extrabold uppercase tracking-widest flex items-center gap-1">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
                  Outbound SMTP Log Dispatch
                </span>
                <span className="text-[9px] font-mono text-slate-500">{lastDispatchedEmail.timestamp}</span>
              </div>

              <div className="space-y-1 text-[10px] font-mono leading-tight">
                <p><span className="text-slate-500">To:</span> <span className="text-slate-200 font-bold select-all">{lastDispatchedEmail.to}</span></p>
                <p><span className="text-slate-500">From:</span> <span className="text-slate-400">auth-mailer@cornerstonesavings.com</span></p>
                <p><span className="text-slate-500">Subject:</span> <span className="text-indigo-300 font-bold">{lastDispatchedEmail.subject}</span></p>
              </div>

              <div className="border-t border-slate-800 pt-1.5 mt-1">
                <p className="text-[10px] text-slate-500 font-bold mb-1">Email Body Draft (Sent to User Inbox):</p>
                <pre className="text-[9px] font-mono bg-slate-950 p-2 rounded text-slate-350 overflow-x-auto whitespace-pre-wrap leading-relaxed max-h-32">
                  {lastDispatchedEmail.body}
                </pre>
              </div>

              <div className="flex items-center gap-1 text-[9px] text-teal-400 font-semibold pt-1">
                <Send className="w-3 h-3 text-teal-400" />
                Notification status: DELIVERED (Simulated)
              </div>
            </div>
          )}
        </div>

        {/* Right column - Staff Accounts Directory List */}
        <div className="lg:col-span-7 bg-white rounded-xl p-5 shadow-sm border border-slate-200 space-y-4">
          <div className="flex justify-between items-center border-b border-slate-150 pb-2.5">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 flex items-center gap-1.5">
              <Key className="w-4 h-4 text-slate-600" />
              Manage Passwords & Directory Access ({staffAccounts.length + 2})
            </h3>
            <span className="text-[10px] font-mono text-slate-404 bg-slate-100 px-2 py-0.5 rounded font-bold uppercase">System Guard</span>
          </div>

          <div className="overflow-x-auto border border-slate-200 rounded-lg">
            <table className="w-full text-left border-collapse text-xs font-sans">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-205 text-slate-600 font-bold">
                  <th className="p-3 min-w-[150px]">Staff Login ID</th>
                  <th className="p-3 min-w-[140px]">Credentials Vault Status / Password</th>
                  <th className="p-3 text-center w-[120px]">Ledger Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {/* Always show official built-in accounts (annotated with Built-in shield) */}
                <tr className="bg-slate-50/40 hover:bg-slate-50/80 transition">
                  <td className="p-3">
                    <p className="font-bold text-slate-850 flex items-center gap-1">
                      officer@cornerstone.com
                      <span className="text-[8px] bg-slate-100 text-slate-600 uppercase border border-slate-200 px-1 py-0.3 rounded font-mono font-bold" title="Built-in system operator">built-in</span>
                    </p>
                    <p className="text-[10px] text-slate-400 font-medium">Cornerstone Officer</p>
                  </td>
                  <td className="p-3 font-mono">
                    <span className="text-slate-400 text-[10px] font-semibold flex items-center gap-1">
                      <Lock className="w-3 h-3" /> Vault Protected (staff123)
                    </span>
                  </td>
                  <td className="p-3 text-center text-slate-400 italic text-[10px]">
                    Root Override Required
                  </td>
                </tr>

                <tr className="bg-slate-50/40 hover:bg-slate-50/80 transition">
                  <td className="p-3">
                    <p className="font-bold text-slate-850 flex items-center gap-1">
                      admin@cornerstone.com
                      <span className="text-[8px] bg-indigo-50 text-indigo-750 uppercase border border-indigo-100 px-1 py-0.3 rounded font-mono font-bold" title="Built-in Administrator">admin</span>
                    </p>
                    <p className="text-[10px] text-slate-400 font-medium font-sans">Global Administrator</p>
                  </td>
                  <td className="p-3 font-mono">
                    <span className="text-slate-400 text-[10px] font-semibold flex items-center gap-1">
                      <Lock className="w-3 h-3" /> Vault Protected (admin123)
                    </span>
                  </td>
                  <td className="p-3 text-center text-slate-400 italic text-[10px]">
                    Root Override Required
                  </td>
                </tr>

                {/* Custom created admin-managed account list */}
                {staffAccounts.map((account) => {
                  const isPasswordRevealed = !!revealedPasswords[account.id];
                  const isCurrentlyEditing = editingStaffId === account.id;

                  return (
                    <tr key={account.id} className="hover:bg-slate-50 transition">
                      <td className="p-3">
                        <p className="font-bold text-indigo-900 select-all">{account.email}</p>
                        <p className="text-[9px] font-mono text-slate-400 mt-0.5">Created: {account.createdAt}</p>
                      </td>
                      <td className="p-3">
                        {isCurrentlyEditing ? (
                          <div className="flex items-center gap-1.5">
                            <input
                              type="text"
                              value={editingPassword}
                              onChange={(e) => setEditingPassword(e.target.value)}
                              className="px-2 py-1 bg-white border border-indigo-400 focus:outline-none rounded text-xs font-mono font-bold text-slate-800 w-full"
                            />
                            <button
                              onClick={() => saveInlineEdit(account.id)}
                              className="bg-emerald-600 hover:bg-emerald-700 text-white px-2 py-1 rounded text-[10px] font-bold cursor-pointer select-none"
                            >
                              Save
                            </button>
                            <button
                              onClick={() => setEditingStaffId(null)}
                              className="bg-slate-200 hover:bg-slate-300 text-slate-700 px-2 py-1 rounded text-[10px] font-bold cursor-pointer select-none"
                            >
                              <X className="w-3 h-3" />
                            </button>
                          </div>
                        ) : (
                          <div className="flex items-center gap-2">
                            <span className="font-mono text-xs font-bold text-slate-800">
                              {isPasswordRevealed ? account.password : '••••••••'}
                            </span>
                            <button
                              onClick={() => togglePasswordReveal(account.id)}
                              className="text-slate-400 hover:text-slate-600 cursor-pointer select-none"
                              title={isPasswordRevealed ? 'Hide passcode' : 'Reveal passcode'}
                            >
                              {isPasswordRevealed ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                            </button>
                          </div>
                        )}
                      </td>
                      <td className="p-3 text-center">
                        <div className="flex items-center justify-center gap-1">
                          {!isCurrentlyEditing && (
                            <button
                              onClick={() => startEditing(account.id, account.password)}
                              className="p-1 text-slate-550 hover:text-indigo-650 hover:bg-indigo-50 border border-transparent hover:border-indigo-100 rounded cursor-pointer select-none"
                              title="Update Passcode"
                            >
                              <Edit2 className="w-3.5 h-3.5" />
                            </button>
                          )}
                          <button
                            onClick={() => {
                              if (confirm(`Are you sure you want to completely revoke credentials for directory ID ${account.email}?`)) {
                                onDeleteStaff(account.id);
                              }
                            }}
                            className="p-1 text-slate-550 hover:text-rose-650 hover:bg-rose-50 border border-transparent hover:border-rose-100 rounded cursor-pointer select-none"
                            title="De-commission Directory ID"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}

                {staffAccounts.length === 0 && (
                  <tr>
                    <td colSpan={3} className="p-6 text-center text-slate-400 italic">
                      No custom team operator directory IDs found. Utilize the commission builder panel on the left to invite other operators to the Cornerstone system!
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>

      </div>

    </div>
  );
}
